/*
    COPYRIGHT 2007-2012, 2020

    This file is part of Lib Descriptors.

    Lib Descriptors is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Lib Descriptors is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Lib Descriptors. If not, see <http://www.gnu.org/licenses/>.
    
    Otavio A. B. Penatti - otavio_at_penatti_dot_com
    https://github.com/otaviopenatti/libdescriptors
*/
#include "libdescriptors.h"

int main(int argc, char** argv)
{
  Ap_FeatureVector1D *cbc1=NULL;
  Ap_FeatureVector1D *cbc2=NULL;
  FeatureVector1D *wcbc1=NULL;
  FeatureVector1D *wcbc2=NULL;
  double distance;
  int n1, n2;
  int i;

  if (argc != 3) {
    fprintf(stderr,"Usage: cbc_distance <fv1_path> <fv2_path>\n");
	fprintf(stderr,"\tfv_path: path to the feature vector files corresponding to the images from which the user wants to compute the distance\n");
	fprintf(stderr,"Remark:\n\tThis program computes the distance between 2 images.\n");
	fprintf(stderr,"\tThe arguments are files generated by the 'extraction' program.\n");
	fprintf(stderr,"\tThe distance between the two images is printed on stdout.\n");
    exit(-1);
  }  

  cbc1 = ReadAp_FeatureVector1D(argv[1], &n1);
  cbc2 = ReadAp_FeatureVector1D(argv[2], &n2);

  wcbc1 = CreateFeatureVector1D(n1);
  for (i=0; i<n1; i++)
    wcbc1->X[i] = cbc1[i]->X[5];

  wcbc2 = CreateFeatureVector1D(n2);
  for (i=0; i<n2; i++)
    wcbc2->X[i] = cbc2[i]->X[5];

  distance=IRM(cbc1, wcbc1, cbc2, wcbc2, CBCRegionDistance);
  printf("%lf\n",distance);

  for (i=0; i<n1; i++)
    DestroyFeatureVector1D(&cbc1[i]);
  free(cbc1);

  for (i=0; i<n2; i++)
    DestroyFeatureVector1D(&cbc2[i]);
  free(cbc2);

  DestroyFeatureVector1D(&wcbc1);
  DestroyFeatureVector1D(&wcbc2);

  return(0);
}
